language: python
python:
  - 2.7
  - 3.3
  - 3.4
# command to install dependencies

env: PYTHONPATH="$PWD/node:$PYTHONPATH"

services:
  - mysql

before_install:
  - sudo apt-get install libcrypto++-dev

install:
  - "pip install coverage coveralls"
  - "python setup.py install"
  - "git clone https://github.com/wiggzz/downstream-node.git node"
  - "cd node ; pip install -r requirements.txt ."
  - "mkdir data && cd data"
  - "curl -o GeoLite2-City.mmdb.gz http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz"
  - "gunzip GeoLite2-City.mmdb.gz"
  - "cd ../.."

before_script:
  - 'mysql -e "create database if not exists downstream;" -u root'
  - "cd node"
  - "python runapp.py --initdb"
  - "python runapp.py --generate-chunk 32768"
  - 'mysql downstream -e "insert into addresses (address, crowdsale_balance) values (''19qVgG8C6eXwKMMyvVegsi3xCsKyk3Z3jV'',10000);" -u root'
  - "nohup python runapp.py &"
  - "cd .."

after_success:
  - "coveralls --verbose"

# command to run tests
script:
  - coverage run setup.py test -a "--doctest-modules --pep8 -v tests/ downstream_farmer/"
  - coverage report -m --include="downstream_farmer/*"
  - "downstream  --quiet -n 2 'http://localhost:5000'"
  - cat node/nohup.out

notifications:
  slack:
    secure: Avmt9x3eMk8f7TpY7OmxvQJTUkpcJjnEZ+aPenh4dO+K6WWmHffK82zK8M+PN5WA7gfffEyPElrfPdMQYNVMmeFzt1S7vu6lvxDh/p/7RnRb3wE6JdpJPngEOf2HFPaFuh9Uqp2zoSleeIHs/n8Qf6HURx5GbzskQ350oWuB06E=